dependencies:
    - python=3.7
    - sphinx=1.8.5 
    - setuptools
    - swig
    - cmake
    - bison=3.0
    - flex=2.6
    - pip
    - pip:
        - sphinx-autodoc-typehints==1.5.0
        - m2r

